### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by kirillgroshkov** [nicolo-ribaudo/jest-light-runner#1]
Feature request: would be awesome if it supported typescript compilation (no type-checking needed).

Maybe something simple like `esbuild` transformer can be added for `*.ts` files, that'll cover 99% of the common needs.

Awesome runner, by the way!

**Comment by cspotcode** [comment]
I bet you can use ts-node's ESM loader to do this today.  Turn on swc mode for speed.

**Comment by cspotcode** [comment]
I made a demo combining ts-node with this test runner:
https://github.com/TypeStrong/ts-node-repros/tree/jest-light-runner/

I see that esmock is mentioned in the readme.  If you want to combine ts-node with esmock or any other loader, try this:
https://www.npmjs.com/package/@cspotcode/multiloader
Or wait for node to release loader chaining support.

**Comment by kirillgroshkov** [comment]
@cspotcode awesome, it works!

I'll close the issue then! 👍

**Comment by cspotcode** [comment]
Any chance this can be added to the README?

**Comment by nicolo-ribaudo** [comment]
Thank you @cspotcode! I'll create an "examples" folder that shows both this and how to mock ES modules using a loader.

**Comment by iambumblehead** [comment]
from this PR and discussion https://github.com/iambumblehead/esmock/pull/155 we found that, using the latest node v18.9.0...

<details>
<summary><b>jest + jest-light-runner + ts-node/esm do not work,</b> cc @cspotcode</summary>

```json
{
  "type": "module",
  "description": "esmock unit tests, jest with ts and jest-light-runner",
  "dependencies": {
    "ts-node": "^10.9.1",
    "jest": "^29.0.3",
    "jest-light-runner": "0.4.0",
    "run-script-os": "^1.1.6"
  },
  "jest": {
    "runner": "jest-light-runner"
  },
  "scripts": {
    "test:default": "NODE_OPTIONS=\"--loader=ts-node/esm\" jest test.ts",
    "test:win32": "set NODE_OPTIONS=\"--loader=ts-node/esm\" && jest test.ts",
    "test": "run-script-os"
  }
}
```
</details>

```console
 FAIL  ./test.ts
  ● Test suite failed to run

    thrown: Object {

        "diagnosticCodes": Array [
          2593,
          2304,
        ],
      }

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.582 s
Ran all test suites matching /test.ts/i
```


<details>
<summary><b>jest + jest-light-runner + tsm are working</b></summary>

```json
{
  "type": "module",
  "description": "esmock unit tests, jest with ts and jest-light-runner",
  "dependencies": {
    "tsm": "^2.2.2",
    "jest": "^29.0.3",
    "jest-light-runner": "0.4.0",
    "run-script-os": "^1.1.6"
  },
  "jest": {
    "runner": "jest-light-runner"
  },
  "scripts": {
    "test:default": "NODE_OPTIONS=\"--loader=tsm\" jest test.ts",
    "test:win32": "set NODE_OPTIONS=\"--loader=tsm\" && jest test.ts",
    "test": "run-script-os"
  }
}
```
</summary>

</details>

```console
 PASS  ./test.ts
  ✓ should pass a test when using jest

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.792 s
Ran all test suites matching /test.ts/i
```

**Comment by cspotcode** [comment]
Looks like you do not want typechecking, and you got a typechecking error here.  So I would turn off typechecking.  `transpileOnly` should do the trick.

**Comment by iambumblehead** [comment]
@cspotcode thank you, with this tsconfig.json, the ts-node test is passing. I will update the comment above shortly,
```json
{
  "extends": "ts-node/node16/tsconfig.json",
  "ts-node": {
    "transpileOnly": true,
    "files": true
  },
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "module": "ESNext",
    "moduleResolution": "node"
  }
}
```

**Comment by cspotcode** [comment]
Sounds good, you can also remove the `files` option since that one only affects typechecking.  With `transpileOnly` enabled, it has no effect.

**Comment by iambumblehead** [comment]
<details>
<summary>the person who opened the issue at esmock, @cyberwombat, also wants to use a jest.config.ts file that looks like this,</summary>

```json
export default {
  testEnvironment: 'jest-environment-node',
  setupFiles: ['./test/setup.ts'],
  setupFilesAfterEnv: ['./test/bootstrap.ts'],
  transform: {
    '^.+\\.tsx?$': [
      'ts-jest',
      {
        useESM: true,
        diagnostics: false,
        compilerHost: true,
        incremental: true
      }
    ]
  },
  moduleNameMapper: {
    '^(\\.{1,2}/.*)\\.js$': '$1',
    '^lib/(.*)$': 'src/lib/$1',
   ...
  },
  extensionsToTreatAsEsm: ['.ts'],
  testPathIgnorePatterns: ['<rootDir>/dist', '.history'],
  modulePaths: ['<rootDir>/src', '<rootDir>/test', '<rootDir>'],
  preset: 'ts-jest'
}
```
</details>

Is it possible to support this, while using jest-light-runner with --loader=ts-node/esm?

**Comment by iambumblehead** [comment]
ts-node fails in windows CI pipeline, seemingly because of the slash "/" in "ts-node/esm"
```json
{
  "scripts": {
    "test:win32": "set NODE_OPTIONS=\"--loader=ts-node/esm --loader=esmock\" && jest esmock.node-jest.test.ts"
  }
}
```

https://github.com/iambumblehead/esmock/actions/runs/3091643663/jobs/5001967546
```console
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './esm --loader=esmock' is not defined by "exports" in D:\a\esmock\esmock\tests\tests-jest-ts\node_modules\ts-node\package.json imported from D:\a\esmock\esmock\tests\tests-jest-ts\
    at new NodeError (node:internal/errors:393:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:340:9)
```

**Comment by cspotcode** [comment]
Mistake in your quoting

`Package subpath './esm --loader=esmock' is not defined by "exports"`

It thinks the subpath is this full string:

`esm --loader=esmock`

Cuz of a mistake in quoting

**Comment by iambumblehead** [comment]
it seems the solution is so obvious, no explanation is needed :)  but I do not know the solution. I think I understand the problem you are pointing out, but I don't know how to solve it

**Comment by liuxingbaoyu** [comment]
https://stackoverflow.com/questions/535975/dealing-with-quotes-in-windows-batch-scripts

Does this work?
`    "test:win32": "set \"NODE_OPTIONS=--loader=ts-node/esm --loader=esmock\" && jest esmock.node-jest.test.ts"
`
