### ISSUE TITLE
Support source-maps

### ISSUE THREAD

**Issue by kayahr** [nicolo-ribaudo/jest-light-runner#17]
When tests fail in my typescript project then Jest shows JavaScript stacktraces which are not very helpful. This can be fixed by doing this in every test file:

```typescript
import "source-map-support/register";
```

Maybe it would be a good idea to do this by default directly in jest-light-runner?

**Comment by nicolo-ribaudo** [comment]
Does this work by just adding
```js
setupFiles: ["source-map-support/register"]
```
in Jest's configuration?

If it does, I'd prefer to just document it.

**Comment by 2xic** [comment]
> Does this work by just adding
> 
> ```js
> setupFiles: ["source-map-support/register"]
> ```
> 
> in Jest's configuration?
> 
> If it does, I'd prefer to just document it.

It worked for me :)
