### ISSUE TITLE
`expect.addSnapshotSerializer()` not working as expected

### ISSUE THREAD

**Issue by fisker** [nicolo-ribaudo/jest-light-runner#35]
Seems the "serializer" is added globally, maybe because we are not running [test files isolatedly](https://github.com/nicolo-ribaudo/jest-light-runner/issues/2)?

I haven't dug into the problem, I'll post what I found.

**Comment by fisker** [comment]
Ah, found this https://github.com/facebook/jest/blob/main/packages/jest-snapshot/src/plugins.ts#L39, so I can backup it and restore after test?

**Comment by SimenB** [comment]
Yeah, just module state. Which works fine in Jest, but caching probably messes up for this runner

**Comment by fisker** [comment]
Is #47 good? Or is there a better solution?

**Comment by SimenB** [comment]
I think that's good. It might make sense for Jest to expose some sort of "reset serializers" API which reset the array to the default (happy to take a PR)? But with the current API I think your approach is good
