### ISSUE TITLE
Respect `--maxWorkers`

### ISSUE THREAD

**Issue by nicolo-ribaudo** [nicolo-ribaudo/jest-light-runner#7]
As suggested by Simen, it should be enough to read `this.#config.maxWorkers` in https://github.com/nicolo-ribaudo/jest-light-runner/blob/9fb6563376cea904bf6653e848c21c15d0a060d6/src/index.js#L10

**Comment by SimenB** [comment]
woo

**Comment by fisker** [comment]
woo woo

**Comment by fisker** [comment]
I just want to say it's so damn fast. Maybe because of this one?

[4m6s](https://github.com/prettier/prettier/runs/5847198949?check_suite_focus=true) vs [2m30s](https://github.com/prettier/prettier/runs/5850376646?check_suite_focus=true)

**Comment by SimenB** [comment]
awesome!

**Comment by fisker** [comment]
Another test [5m8s](https://github.com/prettier/prettier/runs/5847213277?check_suite_focus=true#step:10:6) vs [3m26s](https://github.com/prettier/prettier/runs/5850394820?check_suite_focus=true#step:10:6)

**Comment by nicolo-ribaudo** [comment]
The number of workers definitely affects performance. I hard-coded `os.cpus() / 2` because that was the fastest one on my PC, but probably it depends on the environment.
