### ISSUE TITLE
Importing files using a timestamp query parameter breaks with the `tsx` loader

### ISSUE THREAD

**Issue by JoostK** [nicolo-ribaudo/jest-light-runner#77]
I am experimenting with the [`tsx`](https://github.com/esbuild-kit/tsx)/[`@esbuild-kit/esm-loader`](https://github.com/esbuild-kit/esm-loader) together with `jest-light-runner`, and the inclusion of the current date when importing the test file results in an `ERR_UNKNOWN_MODULE_FORMAT` error (when `--experimental-specifier-resolution=node` is used, Node 18.16.1. Without this option I am running into `ERR_MODULE_NOT_FOUND` because of the `.ts` extension).

I came to realize this is because `jest-light-runner` loads test modules using an additional query parameter, which causes issues with the `tsx` loader. Note that the `ts-node/esm` loader does work, I presume they strip query parameters from the path before passing it through.

https://github.com/nicolo-ribaudo/jest-light-runner/blob/24435e037bc809127e5e0eeb49816164681feb5a/src/worker-runner.js#L103

Removing the ` + "?" + Date.now()` part avoids this problem, allowing the tests to run nicely (and fast, so fast! 🚀) in `runInBand` mode (there's an unrelated issue when using workers, but I haven't looked into that sufficiently yet to tell what's going on).

It is not entirely clear to me what the date is trying to achieve. Is it for circumventing Node's module cache during watch mode? Should `tsx` perhaps identify the query param and strip it (which I assume is what `ts-node` does)?

**Comment by nicolo-ribaudo** [comment]
I think this is a bug in `tsx`: Node.js supports query params in import URL:
- for local imports, it just ignores them
- for http imports, it sends them to the server

`tsx` should support it too.
